### ISSUE TITLE
Bugfixed uci.cpp

### ISSUE THREAD

**Issue by jimablett** [Orbital-Web/Raphael#4]
Hi,

I noticed after compiling the uci version of the engine in Windows that it would not make a move after starting a game in Arena.
Running the engine in the terminal I noticed that I had to enter the 'go' command twice before the command would work.

Modified code below fixes the problem and now uci engine works properly in Arena gui

//uci.cpp

//////////////////////////////////////////////////////////////////////////////////

#define UCI
#include <GameEngine/consts.h>
#include <Raphael/Raphael_v2.0.hpp>
#include <atomic>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

using std::cin;
using std::cout;
using std::ref;
using std::stoi;
using std::stoll;
using std::string;
using std::stringstream;
using std::thread;
using std::vector;

// global vars
const char version[4] = "1.7";
chess::Board board;
Raphael::v2_0 engine("Raphael");
bool halt = false;
bool quit = false;

void setoption(const vector<string>& tokens) {
    if (tokens.size() != 5) return;

    if (tokens[2] == "Hash") {
        int tablesize_mb = stoi(tokens[4]);
        if (tablesize_mb < 1 || tablesize_mb > 2560) return;

        uint32_t tablesize
            = (tablesize_mb * 1024U * 1024) / sizeof(Raphael::TranspositionTable::Entry);
        engine.set_options({.tablesize = tablesize});

        lock_guard<mutex> lock(cout_mutex);
        cout << "Set table size to " << tablesize_mb << "mb (" << tablesize << " entries)\n";
    }
}

void setposition(const vector<string>& tokens) {
    int ntokens = tokens.size();
    if (ntokens < 2) return;

    int i = 2;
    if (tokens[1] == "startpos")
        board.setFen(chess::STARTPOS);
    else if (tokens[1] == "fen") {
        string fen = tokens[2];
        i = 3;
        while (i < ntokens) {
            if (tokens[i] == "moves") break;
            fen += " " + tokens[i];
            i++;
        }
        board.setFen(fen);
    }

    while (++i < ntokens) board.makeMove(chess::uci::uciToMove(board, tokens[i]));
}

void search(const vector<string>& tokens) {
    int ntokens = tokens.size();
    int i = 1;
    int t_remain = 0, t_inc = 0;
    Raphael::v2_0::SearchOptions searchopt;

    while (i < ntokens) {
        if (tokens[i] == "depth") {
            searchopt.maxdepth = stoi(tokens[i + 1]);
            break;
        } else if (tokens[i] == "nodes") {
            searchopt.maxnodes = stoll(tokens[i + 1]);
            break;
        } else if (tokens[i] == "movetime") {
            searchopt.movetime = stoi(tokens[i + 1]);
            break;
        } else if (tokens[i] == "infinite") {
            searchopt.infinite = true;
            break;
        } else if ((whiteturn && tokens[i] == "wtime") || (!whiteturn && tokens[i] == "btime"))
            t_remain = stoi(tokens[i + 1]);
        else if ((whiteturn && tokens[i] == "winc") || (!whiteturn && tokens[i] == "binc"))
            t_inc = stoi(tokens[i + 1]);
        i += 2;
    }

    halt = false;
    engine.set_searchoptions(searchopt);
    sf::Event nullevent;
    engine.get_move(board, t_remain, t_inc, ref(nullevent), ref(halt));
}

void process_command(const string& uci_command) {
    vector<string> tokens;
    stringstream ss(uci_command);
    string token;
    while (ss >> token) tokens.push_back(token);
    if (tokens.empty()) return;

    string& keyword = tokens[0];

    if (keyword == "setoption")
        setoption(tokens);
    else if (keyword == "position")
        setposition(tokens);
    else if (keyword == "go")
        search(tokens);
}

int main() {
    string uci_command;
    Raphael::v2_0::EngineOptions engine_opt;

    while (!quit) {
        if (!getline(cin, uci_command) || uci_command.empty()) {
            continue;
        }

        if (uci_command == "uci") {
            lock_guard<mutex> lock(cout_mutex);
            cout << "id name Raphael " << version << "\n"
                 << "id author Rei Meguro\n"
                 << "option name Hash type spin default 192 min 1 max 2560\n"
                 << "uciok\n";
        } else if (uci_command == "isready") {
            lock_guard<mutex> lock(cout_mutex);
            cout << "readyok\n";
        } else if (uci_command == "ucinewgame") {
            engine.reset();
        } else if (uci_command == "stop") {
            halt = true;
        } else if (uci_command == "quit") {
            halt = true;
            quit = true;
        } else {
            process_command(uci_command);
        }
    }

    return 0;
}

////////////////////////////////////////////////////////////////////////////////////////

regards,
Jim.

**Comment by Orbital-Web** [comment]
Hi Jim,

Thanks a lot for the issue. Just to double check, is this from the latest release? 

I noticed you removed all the multithreading in the script. That was there so the UCI engine can process halt and quit commands while it is running. 

I’m not able to replicate the issue you’re having, though from the looks of things were you perhaps limiting the engine to just a single thread? It’s a bit weird that it works on the second go command. If you don’t mind, would you be able to show me what command you sent to the UCI engine? 

EDIT: this may be the result of some undefined behavior with cout in multiple threads. I may have a fix

**Comment by Orbital-Web** [comment]
I believe the issues are fixed with the latest version. I also noticed another bug regarding invalid moves when the engine starts thinking of a next move before it has processed all of the moves in the position command, which should be now fixed.
Please let me know if you still notice issues.
