### ISSUE TITLE
main doesn't run

### ISSUE THREAD

**Issue by toni-chess** [Orbital-Web/Raphael#5]
![Raphael](https://github.com/user-attachments/assets/b372554b-bf2c-400c-b4ee-5d4cf36c4199)

After downloaded SFML 2.6.0  and copy openal32.dll to Raphael directory....
![Raphael-1](https://github.com/user-attachments/assets/ac9dd318-314e-427d-a5b0-a008eeae58f3)

**Comment by Orbital-Web** [comment]
Hi, thanks for trying our Raphael.
If you don't mind, could you let me know which version of SFML you downloaded (Visual C++, MinGW, 32 or 64bit, etc.)? I've never considered it but it may have an effect on the executable. 
I've also updated the [Release page](https://github.com/Orbital-Web/Raphael/releases/tag/v1.7.6) to include the openal32.dll file. Could you try replacing yours with the one there and see if that fixes it?

Thanks!

**Comment by toni-chess** [comment]
> Hi, thanks for trying our Raphael. If you don't mind, could you let me know which version of SFML you downloaded (Visual C++, MinGW, 32 or 64bit, etc.)? I've never considered it but it may have an effect on the executable. I've also updated the [Release page](https://github.com/Orbital-Web/Raphael/releases/tag/v1.7.6) to include the openal32.dll file. Could you try replacing yours with the one there and see if that fixes it?
> 
> Thanks!

hi again!
I downloaded:....
SFML-2.6.0-windows-vc17-64-bit.zip
SFML-2.6.0-windows-vc17-32-bit.zip
SFML-2.6.0-windows-vc15-64-bit.zip
SFML-2.6.0-windows-gcc-13.1.0-mingw-64-bit.zip
SFML-2.6.0-windows-gcc-13.1.0-mingw-32-bit.zip+
+ yours openal32.dl
...no one works

and Raphael engine doesnot works without these dlls library:
libgcc_s_seh-1.dll
libmcfgthread-1.dll
libstdc++-6.dll
libwinpthread-1.dll

hope you understand my poor english
best regards

**Comment by Orbital-Web** [comment]
No problem, thank you so much for trying those all out.
I just updated the .exe file and engine in the release page. 
Can you try running the new version and see if that fixes the issue?

**Comment by toni-chess** [comment]
> Raphael

Hi there!
The new engine binary works ok, but the main.exe I can't test because Windows Security block it download.

**Comment by Orbital-Web** [comment]
That's great.
I'm not too sure if I can do anything about Windows Security block. You'll probably have to unblock the file by right clicking it and going into its properties to be able to run it. If you're unsure if the file is safe, you can always check using [this site](https://www.virustotal.com/gui/home/upload). 

As a side note, are you running main.exe from the terminal? Just double clicking the executable won't work as the executable has a few required command line arguments.
You'll want to open cmd and type `main.exe Human me Raphael engine` to play a match against the engine.

**Comment by toni-chess** [comment]
> That's great. I'm not too sure if I can do anything about Windows Security block. You'll probably have to unblock the file by right clicking it and going into its properties to be able to run it. If you're unsure if the file is safe, you can always check using [this site](https://www.virustotal.com/gui/home/upload).
> 
> As a side note, are you running main.exe from the terminal? Just double clicking the executable won't work as the executable has a few required command line arguments. You'll want to open cmd and type `main.exe Human me Raphael engine` to play a match against the engine.

So, I downloaded it but when I run it from cmd it closes immediately.

**Comment by Orbital-Web** [comment]
Could you show me how you ran it from cmd please? Thanks a lot.

**Comment by toni-chess** [comment]
> Could you show me how you ran it from cmd please? Thanks a lot.

there is nothing to show you about main.exe but i'll show to you how i run Raphael engine from cmd
![Raphael 1 7 6 3](https://github.com/user-attachments/assets/c4866de3-7079-472c-8cae-218223776cb6)

ok I did a batch file (main.exe Human me Raphael engine) and and i get this screen:

E:\Chess\Engines\HP\Raphael>main.exe Human me Raphael engine
Failed to load image "src/assets/themes/tartiana/wP.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/wN.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/wB.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/wR.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/wQ.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/wK.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/bP.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/bN.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/bB.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/bR.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/bQ.png". Reason: Unable to open file
Failed to load image "src/assets/themes/tartiana/bK.png". Reason: Unable to open file
Failed to load image "src/assets/themes/check.png". Reason: Unable to open file
Failed to load font "src/assets/fonts/Roboto-Regular.ttf" (failed to create the font face)
Failed to open sound file "src/assets/sounds/Move.ogg" (couldn't open stream)
Failed to open sound file "src/assets/sounds/Capture.ogg" (couldn't open stream)
Failed to open sound file "src/assets/sounds/GenericNotify.ogg" (couldn't open stream)
Starting match 1 of 1
Warning, no move returned. Remaining time of player: 600.00

**Comment by Orbital-Web** [comment]
Sorry, I meant how did you run main.exe from the command line? Did you do `main.exe Human me Raphael engine` inside cmd (not double clicking main.exe file)?

**Comment by toni-chess** [comment]
> Sorry, I meant how did you run main.exe from the command line? Did you do `main.exe Human me Raphael engine` inside cmd (not double clicking main.exe file)?

Sorry, did you see my edited message above?

**Comment by Orbital-Web** [comment]
Thanks a lot, I see the issue and it should now be fixed.
You'll have to go to the release page one more time and unzip main.zip. 
You can then try starting main.exe inside the main folder the same way as you just did and it should work.

**Comment by toni-chess** [comment]
> Thanks a lot, I see the issue and it should now be fixed. You'll have to go to the release page one more time and unzip main.zip. You can then try starting main.exe inside the main folder the same way as you just did and it should work.

now shows the GUI but unable to make any move, it looks like e picture  :)

**Comment by Orbital-Web** [comment]
Thanks for catching the issue. 
It turns out it was a really weird bug due to enabling compiler optimizations. 
It should (finally) be all fixed in the latest release... hopefully.
